services:
  quiz-api:
    build: .
    container_name: quiz-api
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: quiz
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    restart: always

  db:
    image: mysql:8.0
    container_name: quiz-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quiz-phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
